### ISSUE TITLE
Discriminate between windows & linux containers

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/spec#109]
Windows containers and Linux containers do not share feature parity. 

Discriminating between the two at the spec level would allow ops to maintain portability by being explicit in their requirements. 

It's proposed we remove the existing `container` type and replace it with two new types:
`windowsContainer`
`linuxContainer`

**Comment by chrisdostert** [comment]
so this is shaping up to look something like:
```yaml
container:
  # requires either linux or windows
  linux:
    # linux container specific attributes
  windows:
    # windows container specific attributes
```

@zachpuck @psamaan @sai-li @petedv
