### ISSUE TITLE
Allow path expansion in sub op call outputs

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/spec#122]
Example:
```yaml
outputs:
  dstFile:
    file: {}
run:
  op: 
    pkg: { ref: xyz }
    outputs: { dstFile: $(zyxOutputDir)/theirFile.txt }
```
