### ISSUE TITLE
Allow interpolation in container dir/file binds

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/spec#124]
```yaml
container:
  files:
    $(rootPath)/some-dir/$(descendantPath)/$(fileName).$(fileExtension)
  dirs:
    $(rootPath)/some-dir/$(descendantPath)
```
