### ISSUE TITLE
Dir construction syntax in sub op inputs

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/spec#129]
```yaml
op:
  pkg: { ref: xyz }
  inputs: 
    # where /base exists in pkg & file1/dir1 are in scope
    someDir: /base/{ childFile: $(file1), childDir: { grandChild: $(dir1) } }
```

this would results in pkg xyz being passed someDir w/ value:
```
/ 
  |-- childFile
  # ~ contents of /base
  |-- childDir
    |--grandChild
      # ~ contents of dir1
```
