### ISSUE TITLE
Pkg file reference ambiguity

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/spec#152]
## problem
```yml
op:
  inputs: 
    str: /file/path
  # snipped
```
assuming str is an input of type string, how should we interpret `/file/path`?
is it the literal string `/file/path` or is it the content of the file at pkg path `/file/path`

### 1. / for pkg fs dereference;  \ to escape

```yml
op:
  inputs:
    str1: \/treated/as/string
    str2: /treated/as/path
  # snipped
```

### 2. @() for pkg fs dereferencing

```yml
op:
  inputs:
    str: @(treated/as/path)
  # snipped
```

### 3. $(/) for pkg fs dereferencing

```yml
op:
  inputs:
    str: $(/treated/as/path)
  # snipped
```

### 4. (/) for pkg fs dereferencing

```yml
op:
  inputs:
    str: (/treated/as/path)
  # snipped
```

### get content of pkg file
```yml
op:
  inputs:
    solution1: /file
    solution2: @(file)
    solution3: $(/file)
    solution4: (/file)
  # snipped
```

### get content of pkg file by scope file content
```yml
op:
  inputs:
    solution1: /$(file)
    solution2: @($(file))
    solution3: $(/$(file))
    solution4: (/$(file))
  # snipped
```

### get content of pkg file by pkg file content
```yml
op:
  inputs:
    solution1: /$(/$(file))
    solution2: @(@(file))
    solution3: $(/$(/file))
    solution4: (/(/file))
  # snipped
```

### join content of pkg file & string
```yml
op:
  inputs:
    solution1: # not possible
    solution2: @(file)/string
    solution3: $(/file)/string
    solution4: (/file)/string
  # snipped
```

### join content of 2 pkg files
```yml
op:
  inputs:
    solution1: # not possible
    solution2: @(filename1)@(filename2)
    solution3: $(/filename1)$(/filename2)
    solution4: (/filename1)(/filename2)
  # snipped
```
