### ISSUE TITLE
Relative pkg refs ambiguously defined

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/spec#154]
## Problem
currently it is not well defined how op2 would reference one op1 vs the other in the following scenario:
```
.opspec
|--op1
|--op2
   |--op1
```

## Solution 1: 
treat refs rel to op.yml itself
```yml
name: op2
run:
  serial:
    - op:
        pkg: { ref: ..op1 }
    - op:
        pkg: { ref: op1 }
```

## Solution 2: 
treat refs rel to pkg
```yml
name: op2
run:
  serial:
    - op:
        pkg: { ref: op1 }
    - op:
        pkg: { ref: op2/op1 }
```

## Solution 3: 
de-reference pkgs same as other types
```yml
name: op2
inputs:
  sibOp1:
    dir:
      default: .opspec/op2
run:
  serial:
    - op:
        pkg: $(sibOp1)
    - op:
        pkg: { ref: $(/op1) }
```

## Solution 4: 
ditch relative references
