### ISSUE TITLE
Container file/dir attribute support 

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/spec#155]
### User Story
As an pkg author
I want the ability to specify attributes on container files/dirs
In order to avoid changing them manually inside the container

### Example
```yaml
    fs:
      /rootDir:
        /childDir1:
          /file1.txt:
            data: i'm a text file
            mode: 600
        /childDir2:
          /file2.sh:
            data: |
              #!/usr/bin/env sh
              echo "i'm an executable shell script"
            mode: 777
```

### Reference
https://github.com/moby/tool/blob/master/docs/yaml.md#files
