### ISSUE TITLE
Add support for mounting dirs/files contained in the op bundle

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/spec#64]

**Comment by chrisdostert** [comment]
implementation idea:

add `constants` keyword

example:
```YAML
constants:
  myFile:
    file:
      path: myFile.txt # file at root of bundle
  myDir:
    dir:
      path: . # root of bundle
```
